### ISSUE TITLE
Potential issue with permissions/config

### ISSUE THREAD

**Issue by rianniello** [ausaccessfed/reporting-service#188]
[original description redacted] - @smangelsdorf

**Comment by smangelsdorf** [comment]
The reporting service was designed to work with the rest of AAF's next iteration of tooling, so we don't yet have another system which can provision permissions into it. This means subscribers can only view public reports, and nothing which is specific to (e.g.) IdP administrators.

I'll stress this is part of the design which was signed off when reporting-service was built, and **not** a bug. (However obviously inconvenient it may be.)

The existing reports in Federation Registry will continue to function as they always have.
