### ISSUE TITLE
Building rails assets fails after latest dependency updates

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [ausaccessfed/reporting-service#240]
Hi,

I've just tried rolling out the latest changes merged in #239 .

And my deployment failed on `rails assets:precompile` with:
```
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
```

After some digging into the changes, I found #239  updated the `execjs` gem from 2.7.0 to 2.8.1.

And this version of execjs drops support for TheRubyRacer JS engine built into Ruby - with the justification it isn't supported on Ruby 3: https://github.com/rails/execjs/commit/e44130562d2cd1741b3886c83d82c6623429479d

While this could be also solved by installing one of the supported JS engines - as per https://github.com/rails/execjs/blob/master/README.md, the easiest solution might be pinning execjs to 2.7.0.

@bradleybeddoes , your thoughts?

Cheers,
Vlad

**Comment by rianniello** [comment]
Hi @vladimir-mencl-eresearch @waldofouche has been looking into this one in our other projects. He will address this next week :)

**Comment by vladimir-mencl-eresearch** [comment]
Ah, and I see this gets also touched on in ausaccessfed/validator-service#215 (removing therubyracergem) - from the comment there, is the intention to expect that server will have nodejs installed? (ausaccessfed/validator-service#214)
